print('')
print(20*'=')
print('')
v = float(input('Quanto dinheiro você tem? R$'))
print('')
print('Seus R${:.2f} convertidos em dólares são equivalentes a ${:.2f}'.format(v,v/4.85))
print('')
print(20*'=')
print('')