print('')
print(20*'=')
print('')
L = float(input('Largura da parede: '))
print('')
A = float(input('Altura da parede: '))
print('')
print(20*'=')
print('')
print('Sua parede tem a dimensão de {:.2f}x{:.2f} e sua área é de {:.2f}m². \nPara pintar essa parede, serão necessários {:.1f}L de tinta.'.format(L,A,L*A,(L*A)*0.1))
print('')
print(20*'=')
print('')