print('')
print(20*'=')
print('')
p = float(input('Digite o preço do produto: '))
print('')
d = float(input('Digite a porcentagem do desconto: '))
print('')
print(20*'=')
print('')
print('O produto que custa R${:.2f}, com {:.2f}% de desconto passa a custar R${:.2f}.'.format(p,d,(p/100)*(100-d)))
print('')
print(20*'=')
print('')