print('')
print(20*'=')
print('')
c = float(input('Informe a temperatura em ºC: '))
print('')
print(20*'=')
print('')
print('{:.2f}ºC é igual a {:.2f}ºF'.format(c,(c*1.8)+32))
print('')
print(20*'=')
print('')