print('')
print(20*'=')
print('')
c = int(input('Por quantos dias o carro foi alugado? '))
print('')
k = int(input('Quantos km rodados? '))
print('')
print(20*'=')
print('')
print('O valor a pagar é de R${:.2f}.'.format((c*60)+(k*0.15)))
print('')
print(20*'=')
print('')